name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install and build
        run: npm install && npm run build
        
      - name: Install gh-pages
        run: |
          sudo chown -R $USER /usr/local/lib/node_modules/
          sudo chown -R $USER /usr/local/bin/
          sudo chown -R $USER /usr/local/share/
          npm i gh-pages -g
        
      - name: Deploy
        run: |
          git config --global user.email "siva.medapati@blueyonder.com"
          git config --global user.name "Siva Medapati"
          npm run deploy
