name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install and build
        run: npm install && npm run build
        
      - name: run
        run: |
          ls -la /usr/local/lib/node_modules
          whoami
      - name: Install gh-pages
        run: npm i gh-pages -g
        
      - name: Deploy
        run: npm run deploy
